services:
  # Le site web (le code)
  app:
    build: ./app
    tty: true 
    stdin_open: true
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db

  server: # BACKEND
    build: ./server
    ports:
      - "5000:5000"
      - "5555:5555" # <-- LIGNE pour Prisma Studio
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=${DATA_BASE_URL}
    depends_on:
      - db

  # La base de donnÃ©es
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: goal_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: