services:
  # Ton site web (le code)
  app:
    build: . # Il va chercher le "Dockerfile" dans le dossier actuel
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Le fameux "tunnel" pour le développement
    depends_on:
      - db # On attend que la BDD soit lancée avant de démarrer le site

  # Ta base de données
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: goal_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data # Pour ne pas perdre tes données !

volumes:
  postgres_data:
